
name: CI
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/1440 * * * *'

jobs:
  test:
    # Job name is Test
    name: Test
    # This job runs on macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.0,name=iPhone 8']
        xcode: ['/Applications/Xcode_12_beta.app/Contents/Developer']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Dependencies
        run: |
          sudo gem install cocoapods
          pod repo update
        env:
          DEVELOPER_DIR: ${{ matrix.xcode }}
      - name: Build
        run: pod lib lint --use-libraries --allow-warnings || pod lib lint --allow-warnings
